cake-contrib/Cake.Issues.EsLint

src/Cake.Issues.EsLint/EsLintIssuesAliases.cs

Add EsLintIssuesProviderTypeName alias
Fixes #2

(GH-2) Add EsLintIssuesProviderTypeName alias

---

cake.config
setup.cake
tools/packages.config

Update to Cake 0.23.0 for compatibility with latest Cake.Recipe
Fixes #8

(GH-8) Upgrade to Cake 0.23.0

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Update to Cake.Issues 0.2.0 Beta 2
Fixes #10

(GH-10) Update to Cake.Issues 0.2.0 Beta 2

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Build against Cake 0.28.0
Fixes #14

(GH-14) Build against Cake 0.28.0

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint.Tests/JsonFormatTests.cs
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj
src/Cake.Issues.EsLint/EsLintIssuesAliases.cs
src/Cake.Issues.EsLint/EsLintIssuesProvider.cs
src/Cake.Issues.EsLint/ILogFileFormat.cs
src/Cake.Issues.EsLint/JsonFormat.cs
src/Cake.Issues.EsLint/LogFileFormat.cs

Update to Cake.Issues 0.3.0
Fixes #13

(GH-13) Update to Cake.Issues 0.3.0

---

tools/packages.config

Build with Cake 0.29.0
Fixes #19

(GH-19) Build with Cake 0.29.0

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Update Cake.Issues to 0.4.0-beta.1
Fixes #21

(GH-21) Update Cake.Issues to 0.4.0-beta.1

---

nuspec/nuget/Cake.Issues.EsLint.nuspec

Use jsDelivr for icon since RawGit will shutdown

Use jsDelivr for icon

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Build against Cake 0.33.0
Fixes #48

(GH-48) Build against Cake 0.33.0

---

setup.cake

Disable Shouldly from code coverage

Disable Shouldly from code coverage

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint.Tests/EsLintIssuesSettingsTests.cs
src/Cake.Issues.EsLint.Tests/LogFileFormat/JsonLogFileFormatTests.cs
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Update to Cake.Issues 0.7.0-beta003 
Fixes #49

 (GH-49) Update to Cake.Issues 0.7.0-beta003 

---

README.md
nuspec/nuget/Cake.Issues.EsLint.nuspec

Website changed to cakeissues.net
Fixes #70

(GH-70) Change website to cakeissues.net

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj
src/Cake.Issues.EsLint/LogFileFormat/JsonLogFileFormat.cs

Update Cake.Issues to 0.8.0
Fixes #87

(GH-87) Update Cake.Issues to 0.8.0

---

docs/features.md
src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj
src/Cake.Issues.EsLint/LogFileFormat/JsonLogFileFormat.cs

Update to Cake.Issues 0.9.0 Beta 2
Fixes #117

(GH-117) Update to Cake.Issues 0.9.0 Beta 2

---

docs/features.md
src/Cake.Issues.EsLint.Tests/LogFileFormat/JsonLogFileFormatTests.cs
src/Cake.Issues.EsLint/LogFileFormat/JsonLogFileFormat.cs

Provide `IIssue.Column`
Fixes #119

(GH-119) Provide `IIssue.Column`

---

src/Cake.Issues.EsLint/EsLintIssuesAliases.IssueProvider.cs
src/Cake.Issues.EsLint/EsLintIssuesProvider.cs

Make issue provider type name available on issue provider
Fixes #78

(GH-78) Make issue provider type name available on issue provider

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Build against Cake.Issues 1.0.0 Beta 1
Fixes #155

(GH-155) Build against Cake.Issues 1.0.0 Beta 1

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj

Remove not required PackageReferences

Remove not required PackageReferences

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint.Tests/LogFileFormat/JsonLogFileFormatTests.cs
src/Cake.Issues.EsLint.Tests/Testfiles/JsonLogFileFormat/issueWithoutLineAndColumn.json
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj
src/Cake.Issues.EsLint/LogFileFormat/JsonLogFileFormat.cs

Correctly handles issues which have no line or column reported.
Fixes #165

(GH-165) Handle issues without line or column

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint.Tests/LogFileFormat/JsonLogFileFormatTests.cs
src/Cake.Issues.EsLint.Tests/Testfiles/JsonLogFileFormat/issueWithoutRule.json
src/Cake.Issues.EsLint/LogFileFormat/JsonLogFileFormat.cs

Correctly handles issues which have no rule reported.
Fixes #167

(GH-167) Handle issues without rule

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Builds against Cake 2.0
Fixes #175
Fixes #181

(GH-175) Build against Cake 2.0

---

.appveyor.yml
.vscode/settings.json
azure-pipelines.yml
nuspec/nuget/Cake.Issues.EsLint.nuspec
src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Updates target frameworks to .NET 6 and .NET 7.
Fixes #204

(GH-204) Update target frameworks

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Builds against Cake 3.0 and Cake.Issues 3.0 Beta 1
Fixes #205
Fixes #206

Update to Cake 3.0 and Cake.Issues 3.0

---

recipe.cake

Update build to Cake.Recipe 3.0.1 from Cake.Recipe 3.0 Beta

Update build to Cake.Recipe 3.0.1

---

src/Cake.Issues.EsLint.Tests/Cake.Issues.EsLint.Tests.csproj
src/Cake.Issues.EsLint/Cake.Issues.EsLint.csproj

Build against Cake.Issues 4.0.0-beta0001
Fixes #251

Build against Cake.Issues 4.0.0-beta0001
